name: compare-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compare check
        uses: actions/checkout@master
        with:
          token: ${{ secrets.COMPARE_ID }}
      - run: make install
      - run: make lint
      - run: make test